extraction:
  cpp:
    prepare:
      packages:
        - bison
        - cmake
        - flex
        - g++
        - git
        - libelf-dev
        - libgtest-dev
        - libgmock-dev
        - zlib1g-dev
        - libfl-dev
        - systemtap-sdt-dev
        - binutils-dev
        - llvm-7-dev
        - llvm-7-runtime
        - libclang-7-dev
        - clang-7
        - libbpfcc-dev
    after-prepare:
      - mkdir -p /src
      - git clone https://github.com/libbpf/libbpf.git /src/libbpf
      - cd /src/libbpf/src
      - git checkout v0.8.0
      - CC=gcc make -j$(nproc)
      - PREFIX=/usr/local LIBDIR=/usr/local/lib make install install_uapi_headers

